[package]
name = "beams"
version = "0.1.0"
authors = ["Luka Bratos <luka.bratos@gmail.com>"]

[lib]
name = "beams"
path = "src/lib.rs"

[[bin]]
name = "beams"
path = "src/bin.rs"

[dependencies]
ureq = { version = "*", features = ["json"] }
serde = "1.0"
serde_derive = "1.0"